### ISSUE TITLE
Converting full time to int64 milliseconds

### ISSUE THREAD

**Issue by 5k3105** [KuroiKitsu/go-ass#1]
I see your example converting the parsed time to seconds. I could get the seconds, multiply by 1000 then add in milliseconds. Is this the correct way?

			rawTime := pair.Get("Start")
			sta, _ := ass.ParseTime(rawTime)
			s := (sta/ass.Second).String()
			m1 := ass.Time(sta).Millisecond()
			n1,_ := strconv.Atoi(s)
			st.Start = int64(m1 + n1*1000)

.. and this didn't work for me anyway :)

**Comment by KuroiKitsu** [comment]
`Time` is already in milliseconds. It's just an `int32` with some extra functions (I used `int32` because it's enough for the purposes of this library).

If you need the total milliseconds as `int64`, it's simple:

```go
sta, _ := ass.ParseTime("1:00") // 1 min
milliseconds := int64(sta) // 60000
```

---

Since `Time` is just an `int32`, you can add times directly:

```go
t1, _ := ass.ParseTime("0:01:00.00") // 1 min

t2 := t1 + 5*ass.Second
// t2 := t1 + 5000 // Same as above.

fmt.Printf("%s\n", t2) // 0:01:05.00
```

---

The `Time.Millisecond` function is used when converting the time to string; it returns the milliseconds part of the string. Example:

```go
sta, _ := ass.ParseTime("1:23:45.678") // 1 hour, 23 minutes, 45 seconds, 678 milliseconds
fmt.Printf("%d\n", sta.Millisecond()) // 678
```

---

I should probably add all this to the readme xD.

**Comment by 5k3105** [comment]
I felt I was overlooking something simple :)

Btw, this file type seems to always have the ending songs at the start of the file, or at least a section that's not in linear time order. I wonder why that is? The subtitle renderer is responsible for sorting the times? Seems strange.

Thank you!

**Comment by KuroiKitsu** [comment]
The order of the subtitles depends on the person who made them originally. It's preference. In my case I like to keep the main dialogues first, and everything else at the end (including the opening).

Subtitles are always rendered at the marked times, so their order doesn't really matter.
