### ISSUE TITLE
.Readable() not converting \N

### ISSUE THREAD

**Issue by karlek** [KuroiKitsu/go-ass#1]
Hi! Awesome lib!

I found that newlines (`\N`) are not stripped when using Readable(). Is this intentional?

```ass
Dialogue: 30,0:05:24.40,0:05:27.87,Dialogue,Dark,0,0,0,,You said you had too much to drink \Nlast night and headed straight home.
```
```plaintext
You said you had too much to drink \Nlast night and headed straight home.
```

**Comment by KuroiKitsu** [comment]
Wait, someone is using my lib? This is unexpected xD.

Yeah, `text.Readable` only strips the `{text inside braces}` and any leading/trailing whitespace. Both `"\\N"` and `"\\n"` are left as-is.

However, if you need to replace them with line breaks, you can use the built-in [`strings.Replace`](https://godoc.org/strings#Replace) function:

```go
text := `You said you had too much to drink \Nlast night and headed straight home.`
text = strings.Replace(text, `\N`, "\n", -1)
```

---

Also, since the behavior of the soft-break `"\\n"` depends on the wrapping mode, it would require some extra information to know whether it should be replaced with a space or a `\n` (`U+000A`) character. That's more the job of a higher level library.
